name: Web APIs CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: taiga-family/ci/actions/setup/node@v1.27.0
      - run: npm run build
      - run: npm run lint
      - run: npm run prettier -- --check
      - run: npm run test
        env:
          NODE_OPTIONS: --openssl-legacy-provider
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3.1.4

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true
