name: Web APIs CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: taiga-family/ci/actions/setup/node@v1.71.2
      - run: npm run build
      - run: npm run build:demo
      - run: |
          if [[ "${{ env.SUPPORT_AUTO_PUSH }}" == "true" ]]; then
              npm run prettier -- --write
              npm run stylelint -- --fix
              npm run lint -- --fix
          else
              npm run prettier -- --check
              npm run stylelint
              npm run lint
          fi
      - run: npm run test
      - uses: codecov/codecov-action@v4.5.0
        continue-on-error: true
      - uses: taiga-family/ci/actions/auto/push@v1.71.2
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true
