name: Web APIs CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - uses: taiga-family/ci/actions/setup-node@1.7.6
        with:
          node-version: 12.x
      - run: |
          npm run build
          npm run test
          npm run lint
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
