name: Web APIs CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: taiga-family/ci/actions/setup/node@v1.57.2
      - run: npm run build
      - run: npm run build:demo
      - run: npm run lint
      - run: npm run prettier -- --check
      - run: npm run test
      - uses: codecov/codecov-action@v4.4.1
        continue-on-error: true

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true
