name: ⚠️ Release
on:
  push:
    branches:
      - main
    paths:
      - projects/ng-event-plugins/**
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Bump version as requested
        required: true
        options:
          - minor
          - patch
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message , 'chore(release)')"
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.86.0
      - uses: taiga-family/ci/actions/setup/variables@v1.86.0
      - uses: taiga-family/ci/actions/setup/node@v1.86.0
      - uses: taiga-family/ci/actions/run/release-it@v1.86.0
        with:
          ref: ${{ github.ref }}
          mode: ${{ github.event.inputs.mode }}
          npmToken: ${{ secrets.TAIGA_UI_SCOPE_NPM_TOKEN }}
          githubToken: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

      - uses: taiga-family/ci/actions/run/read-package-json@v1.86.0
        id: info
        with:
          path: ./projects/ng-event-plugins/package.json

      - name: Announce to Telegram
        uses: taiga-family/ci/actions/messenger/telegram/announce@v1.86.0
        with:
          chatId: ${{ secrets.TAIGA_TELEGRAM_CHAT_ID }}
          topicId: ${{ secrets.TAIGA_TELEGRAM_CHAT_THREAD_ID }}
          token: ${{ secrets.TAIGA_TELEGRAM_BOT_TOKEN }}
          version: v${{ steps.info.outputs.version }}
          textLink: ${{ steps.info.outputs.name }}

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
